<?php

/**
 * BaseSite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $domain
 * @property boolean $main
 * @property Doctrine_Collection $aPage
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getName()   Returns the current record's "name" value
 * @method string              getDomain() Returns the current record's "domain" value
 * @method boolean             getMain()   Returns the current record's "main" value
 * @method Doctrine_Collection getAPage()  Returns the current record's "aPage" collection
 * @method Site                setId()     Sets the current record's "id" value
 * @method Site                setName()   Sets the current record's "name" value
 * @method Site                setDomain() Sets the current record's "domain" value
 * @method Site                setMain()   Sets the current record's "main" value
 * @method Site                setAPage()  Sets the current record's "aPage" collection
 * 
 * @package    apo15
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('domain', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('main', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('aPage', array(
             'local' => 'id',
             'foreign' => 'site_id'));
    }
}