<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/01/19 23:05:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=apo15;host=localhost',
  'username' => 'root',
  'password' => 'root',
  'encoding' => 'utf8',
  'attributes' => 
  array (
    'DEFAULT_TABLE_TYPE' => 'INNODB',
    'DEFAULT_TABLE_CHARSET' => 'utf8',
    'DEFAULT_TABLE_COLLATE' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
