<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/01/25 21:25:16
sfConfig::add(array(
  'mod_taggablecomplete_enabled' => true,
  'mod_taggablecomplete_view_class' => 'sfPHP',
));
