<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/01/25 21:25:16
$this->security = array (
  'addtag' => 
  array (
    'is_secure' => true,
  ),
  'removetag' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
