<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/01/20 21:53:14
sfConfig::add(array(
  'mod_aslideshowslot_enabled' => true,
  'mod_aslideshowslot_view_class' => 'sfPHP',
));
