<?php

/**
 * SiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Site');
    }
    

    /**
     * Holds the current site
     * @var Site
     */

    protected $current;

    /**
     * Retrieve a Site by its domain
     *
     * @param string $domain
     * @return Site or false if no site is found
     */

    public function retrieveByDomain($domain)
    {
      return $this->createQuery()->where('domain = ?', $domain)->fetchOne();
    }

    /**
     * Retrieve the main site
     *
     * @return Site or false if no site is found
     */

    public function retrieveMain()
    {
      return $this->createQuery()->where('main = 1')->fetchOne();
    }


    /**
     * Sets the current site
     *
     * @param Site $site
     */

    public function setCurrent(Site $site)
    {
      $this->current = $site;
    }


    public function getCurrent()
    {
      return $this->current;
    }
    

}