<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/01/19 23:05:36
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_a_pager_nb_links' => 5,
  'app_a_vimeo' => NULL,
  'app_a_viddler' => NULL,
  'app_a_slideshare' => NULL,
  'app_a_soundcloud' => NULL,
  'app_a_use_bundled_stylesheet' => true,
  'app_a_global_button_order' => array (
  0 => 'sites',
  1 => 'blog',
  2 => 'events',
  3 => 'media',
  4 => 'categories',
  5 => 'tags',
  6 => 'users',
  7 => 'reorganize',
),
  'app_a_persistent_global_toolbar' => true,
  'app_a_i18n_switch' => false,
  'app_a_i18n_languages' => array (
  0 => 'en',
  1 => 'fr',
  2 => 'de',
  3 => 'es',
  4 => 'ru',
),
  'app_a_routes_register' => false,
  'app_a_default_on' => true,
  'app_a_pretty_english_dates' => true,
  'app_a_manage_candidate_group' => 'editor',
  'app_a_manage_sufficient_group' => 'admin',
  'app_a_edit_candidate_group' => 'editor',
  'app_a_edit_sufficient_group' => 'admin',
  'app_a_view_locked_sufficient_credentials' => 'view_locked',
  'app_a_addslot_button_style' => 'big',
  'app_a_history_button_style' => 'no-label big',
  'app_a_delete_button_style' => 'no-label',
  'app_a_slot_types' => array (
  'aBlog' => 'Blog Posts',
  'aBlogSingle' => 'Blog Post',
  'aEvent' => 'Events',
  'aEventSingle' => 'Event',
  'aImage' => 'Image',
),
  'app_a_templates' => array (
  'a' => 
  array (
    'default' => 'Default Page',
    'home' => 'Home Page',
  ),
  'aMedia' => 
  array (
    'default' => 'Media',
  ),
  'aBlog' => 
  array (
    'default' => 'Blog',
  ),
  'aEvent' => 
  array (
    'default' => 'Events',
  ),
),
  'app_a_use_bundled_layout' => false,
  'app_aAdmin_web_dir' => '/apostrophePlugin',
  'app_aMedia_client_apikey' => 'dummy',
  'app_aMedia_apikeys' => array (
  0 => 'dummy',
),
  'app_aMedia_apipublic' => false,
  'app_aMedia_admin_credential' => 'media_admin',
  'app_aMedia_upload_credential' => 'media_upload',
  'app_aMedia_use_bundled_layout' => false,
  'app_aMedia_embed_codes' => true,
  'app_aEvents_display_calendar' => true,
  'app_aToolkit_indexes' => array (
  0 => 'aPage',
  1 => 'aMediaItem',
),
  'app_sfSyncContent_content' => array (
  0 => 'web/uploads',
  1 => 'data/a_writable',
),
  'app_aimageconverter_path' => '/opt/local/bin',
));
