<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/01/19 23:06:42
sfConfig::add(array(
  'mod_aslideshowslot_enabled' => true,
  'mod_aslideshowslot_view_class' => 'sfPHP',
));
