<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/01/19 23:19:44
sfConfig::add(array(
  'mod_acategoryadmin_enabled' => true,
  'mod_acategoryadmin_view_class' => 'sfPHP',
));
